// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCeS4_TZrRVmkluDpWAEmFwOwzMGyrZXRs',
    appId: '1:1097246901657:web:f414d901b294b4f097bf08',
    messagingSenderId: '1097246901657',
    projectId: 'fir-sicegah-f3e37',
    authDomain: 'fir-sicegah-f3e37.firebaseapp.com',
    storageBucket: 'fir-sicegah-f3e37.firebasestorage.app',
    measurementId: 'G-NMJES4GZZ6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBQryo8Ig4TBA3a4PEfTLHy3QjT0uFnK0I',
    appId: '1:1097246901657:android:f941dc317359f9fc97bf08',
    messagingSenderId: '1097246901657',
    projectId: 'fir-sicegah-f3e37',
    storageBucket: 'fir-sicegah-f3e37.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAhFe-M3ISCsitLU2Txha5b0YgPlFQqQN8',
    appId: '1:1097246901657:ios:db746c0ca27a9e0497bf08',
    messagingSenderId: '1097246901657',
    projectId: 'fir-sicegah-f3e37',
    storageBucket: 'fir-sicegah-f3e37.firebasestorage.app',
    iosBundleId: 'com.example.siCegah',
  );
}
